// Importing the createSlice function from Redux Toolkit to easily create a Redux slice
import { createSlice } from '@reduxjs/toolkit';

// Initial state of the auth slice. Initially, no user is authenticated, and the user is null.
const initialState = {
  user: null,
  isAuthenticated: false,
};

// Creating the auth slice using createSlice function
const authSlice = createSlice({
  name: 'auth', // The name of the slice, which will be used as the key in the Redux store
  initialState, // The initial state defined above
  reducers: {
    // Reducer for handling successful login action
    loginSuccess: (state, action) => {
      state.user = action.payload; // Set the user data from action payload
      state.isAuthenticated = true; // Set isAuthenticated to true
    },
    // Reducer for handling logout action
    logout: (state) => {
      state.user = null; // Reset the user to null
      state.isAuthenticated = false; // Set isAuthenticated to false
    },
  },
});

// Exporting the action creators (loginSuccess and logout) generated by createSlice
export const { loginSuccess, logout } = authSlice.actions;

// Exporting the reducer generated by createSlice. It will be used in the store.
export default authSlice.reducer;
